Repository dottxt-ai/outlines, pull requests merged in 2023-12, with the labels that each got.

#434 Create a new `AsyncOpenai` client for each request
  outlines/models/openai.py
Labels: bug, API models

#444 Update the vLLM example to work with batch requests
  examples/vllm_integration.py
Labels: enhancement

#453 Serve JSON with vLLM using FastAPI and Uvicorn
  outlines/serve/__init__.py
  outlines/serve/serve.py
  outlines/serve/vllm.py
  pyproject.toml
Labels: guided generation, JSON

#467 Update `pip install outlines` in documentation
  docs/assets/images/frontpage_example.png
  docs/index.md
Labels: documentation

#490 Do not import `transformers` at top level in Exllama2 integration
  outlines/models/exllamav2.py
Labels: bug, Open source models
