Repository dottxt-ai/outlines, pull requests merged in 2023-10, with the labels that each got.

#311 Fix JSON schema generation to accept schemas without 'title' property
  outlines/text/json_schema.py
  tests/text/test_json_schema.py
Labels: bug, guided generation, JSON

#313 Update resize padding multiple in `test_transformers_logits_vocab_size`
  tests/text/generate/test_integration_transfomers.py
Labels: bug, huggingface

#314 Avoid unhashable `additional_special_tokens` values in `special_tokens_map`
  outlines/models/transformers.py
  tests/models/test_transformers.py
Labels: bug, huggingface

#321 Add missing sample tests
  tests/text/generate/test_sample.py
Labels: tests

#322 Fix and simplify `walk_fsm`
  outlines/text/fsm.py
  outlines/text/parsing.py
  tests/text/test_fsm.py
Labels: enhancement

#323 Disable eager Numba FSM info construction step in parser
  outlines/text/parsing.py
Labels: enhancement

#324 Add another missing `walk_fsm` condition
  outlines/text/fsm.py
  tests/text/test_fsm.py
Labels: bug

#328 Make sure that indices are available on all relevant devices
  outlines/text/generate/sequence.py
Labels: bug
