Repository dottxt-ai/outlines, pull requests merged in 2023-11, with the labels that each got.

#331 Use MkDocs for the documentation
  .github/workflows/build_documentation.yml
  .github/workflows/publish_documentation.yml
  README.md
  docs/Makefile
  docs/api/continuation.md
  docs/api/fsm.md
  docs/api/index.md
  docs/api/json_schema.md
  docs/api/models.md
  docs/api/parsing.md
  docs/api/prompts.md
  docs/api/regex.md
  docs/api/sample.md
  docs/assets/images/logo.png
  docs/assets/images/normal_computing.jpg
  docs/cookbook/index.md
  docs/examples/dating_profiles.md
  docs/examples/index.md
  docs/get_started.md
  docs/index.md
  docs/make.bat
  docs/overrides/home.html
  docs/overrides/index.html
  docs/overrides/main.html
  docs/reference/choices.md
  docs/reference/index.md
  docs/reference/json.md
  docs/reference/prompting.md
  docs/reference/regex.md
  docs/reference/text_generation.md
  docs/reference/types.md
  docs/source/conf.py
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/overview.rst
  docs/source/reference/batching.rst
  docs/source/reference/controlled_generation.rst
  docs/source/reference/multimodel.rst
  docs/stylesheets/extra.css
  mkdocs.yml
  requirements-doc.txt
Labels: documentation

#358 Implement `text.generate.format` constrained generation
  README.md
  outlines/text/generate/__init__.py
  outlines/text/generate/regex.py
  outlines/text/types.py
  tests/text/generate/test_integration_transfomers.py
  tests/text/generate/test_regex.py
  tests/text/test_types.py
Labels: enhancement

#367 Remove top-level imports of `transformers` and `datasets`
  outlines/models/transformers.py
Labels: enhancement

#372 Add "was this page helpful?" widget
  mkdocs.yml
Labels: documentation

#386 Mention in README `datasets` requirement
  README.md
  docs/get_started.md
Labels: documentation

#390 step by step prompting and colons in prompts
  examples/meta_prompting.py
Labels: bug, examples

#389 Add Chain of Density prompting example
  docs/examples/chain_of_density.md
  docs/examples/dating_profiles.md
  docs/examples/images/chain_of_density.png
  docs/examples/index.md
  mkdocs.yml
Labels: examples, documentation
