Repository dottxt-ai/outlines, pull requests merged in 2024-06, with the labels that each got.

#950 Add statement regarding OS vs closed models
  README.md
Labels: documentation

#932 Support min/max number of digits for numbers in JSON Schema
  outlines/fsm/json_schema.py
  tests/fsm/test_json_schema.py
Labels: structured generation, JSON

#963 Add cerebrium as deployment option in documentation
  docs/cookbook/deploy-using-cerebrium.md
  docs/stylesheets/extra.css
  examples/cerebrium/cerebrium.toml
  examples/cerebrium/main.py
  mkdocs.yml
Labels: documentation

#964 Add link to TGI documentation
  docs/reference/models/tgi.md
  mkdocs.yml
Labels: documentation

#956 Introduce `outlines.models.mlxlm`
  docs/reference/models/mlxlm.md
  mkdocs.yml
  outlines/generate/cfg.py
  outlines/generate/regex.py
  outlines/generate/text.py
  outlines/models/__init__.py
  outlines/models/mlxlm.py
  outlines/processors/__init__.py
  outlines/processors/base_logits_processor.py
  outlines/processors/structured.py
  pyproject.toml
  tests/generate/conftest.py
  tests/generate/test_generate.py
Labels: enhancement

#974 Update Modal refs from stub to app
  docs/cookbook/deploy-using-modal.md
  examples/modal_example.py
Labels: documentation

#939 Mask cache Performance Optimization for vllm
  outlines/integrations/vllm.py
Labels: structured generation, vLLM

#968 update README.md
  README.md
Labels: documentation

#980 Fix samplers documentation
  docs/cookbook/classification.md
Labels: documentation

#972 Ensure regex matches valid JSON for "const" and "enum" with booleans, nulls, and strings
  outlines/fsm/json_schema.py
  tests/fsm/test_json_schema.py
Labels: bug, structured generation, JSON

#960 Add link to docs of Multimodal Structured Generation for CVPR 2nd MMFM Challenge
  docs/community/examples.md
Labels: documentation

#991 Allow escaped strings in `json_schema.py`
  outlines/fsm/json_schema.py
  tests/fsm/test_json_schema.py
Labels: JSON, correctness

#993 Fix use of `os.environ` in documentation
  docs/reference/models/openai.md
Labels: documentation

#995 fix pattern-string in `json_schema.py` by removing anchors
  outlines/fsm/json_schema.py
  tests/fsm/test_json_schema.py
Labels: JSON

#992 Fix Incorrect Token Normalization Method for `LlamaCppTokenizer`
  outlines/models/llamacpp.py
  tests/generate/test_integration_llamacpp.py
Labels: structured generation, tokenization, correctness, llama.cpp

#1000 Add contributors, creation and update date
  docs/welcome.md
  mkdocs.yml
  requirements-doc.txt
Labels: documentation

#1002 Add SimToM prompt recipe
  docs/cookbook/images/simtom.png
  docs/cookbook/index.md
  docs/cookbook/simtom.md
  mkdocs.yml
Labels: documentation

#996 Ensure `models.llamacpp` Doesn't Have Implicit `max_tokens`
  outlines/models/llamacpp.py
  tests/generate/test_integration_llamacpp.py
Labels: llama.cpp

#1003 fix `models.mlxlm` whitespace prefix handling
  outlines/models/mlxlm.py
  tests/generate/conftest.py
  tests/generate/test_generate.py
Labels: tokenization

#1008 Add asknews example
  docs/community/examples.md
Labels: documentation

#998 Improve `outlines.processors`, add integration tests to test_generate.py
  benchmarks/bench_processors.py
  outlines/__init__.py
  outlines/models/mlxlm.py
  outlines/processors/__init__.py
  outlines/processors/base_logits_processor.py
  outlines/processors/structured.py
  tests/generate/test_generate.py
Labels: enhancement, structured generation, run_benchmarks
