Repository dottxt-ai/outlines, pull requests merged in 2024-07, with the labels that each got.

#1012 Abridged version of the .txt article on Coding For Structured Generat…
  docs/cookbook/images/coding_structure_diagram.png
  docs/cookbook/structured_generation_workflow.md
Labels: documentation

#1013 `RegexFSM`: Cache Legal-Token Mask as `torch.Tensor` to Improve Performance
  benchmarks/bench_processors.py
  docs/community/contribute.md
  outlines/fsm/guide.py
  tests/fsm/test_fsm.py
  tests/fsm/test_guide.py
Labels: optimization, structured generation, run_benchmarks, regex

#1034 Update file contributors style for docs
  docs/stylesheets/extra.css
Labels: documentation

#1042 Add QA with Citations example to the Cookbook
  docs/cookbook/qa-with-citations.md
  mkdocs.yml
Labels: documentation

#1040 Fix mamba integration by making it a variant of `outlines.models.transformers`
  docs/reference/models/mamba.md
  docs/reference/models/transformers.md
  outlines/models/__init__.py
  outlines/models/mamba.py
  outlines/models/transformers.py
  tests/generate/test_generate.py
Labels: enhancement, mamba

#1046 add fallback tokenizer
  outlines/models/openai.py
Labels: enhancement, API models

#1049 Add Knowledge Graph Extraction example to the Cookbook
  docs/cookbook/images/knowledge-graph-extraction.png
  docs/cookbook/knowledge_graph_extraction.md
  mkdocs.yml
Labels: examples, documentation

#1052 Introduce `outlines.models.transformers_vision`
  docs/reference/models/transformers_vision.md
  outlines/generate/api.py
  outlines/generate/fsm.py
  outlines/generate/regex.py
  outlines/generate/text.py
  outlines/models/__init__.py
  outlines/models/transformers_vision.py
  pyproject.toml
  tests/generate/test_api.py
  tests/generate/test_generate.py
Labels: transformers vision

#1053 Use `outlines.processors` and `SequenceGeneratorAdapter` for `outlines.models.vllm`
  outlines/generate/choice.py
  outlines/generate/format.py
  outlines/generate/fsm.py
  outlines/generate/json.py
  outlines/generate/regex.py
  outlines/generate/text.py
  outlines/models/vllm.py
  outlines/processors/base_logits_processor.py
  outlines/processors/structured.py
  tests/generate/conftest.py
  tests/generate/test_generate.py
Labels: structured generation, vLLM

#1057 Modal documentation: fix deprecated memory= parameter
  docs/cookbook/deploy-using-modal.md
Labels: examples, documentation

#1058 Documentation: Fix failing Modal example
  docs/cookbook/deploy-using-modal.md
Labels: examples, documentation

#1064 Add link to Multimodal Structured Generation (MMSG) library to docs
  docs/community/examples.md
Labels: documentation

#1072 Fix link to `mamba` model reference
  mkdocs.yml
Labels: documentation
