Repository dottxt-ai/outlines, pull requests merged in 2024-08, with the labels that each got.

#1089 Fix coverage `exclude_lines` setting for ellipsis
  pyproject.toml
Labels: bug, tests

#1090 Add ReAct agent example
  docs/cookbook/index.md
  docs/cookbook/react_agent.md
  mkdocs.yml
Labels: examples, documentation

#1094 Include SPDX license info in project metadata
  pyproject.toml
Labels: enhancement

#1096 Fix details in the documentation
  docs/cookbook/chain_of_thought.md
  docs/cookbook/dating_profiles.md
  docs/cookbook/index.md
  docs/cookbook/knowledge_graph_extraction.md
  docs/cookbook/qa-with-citations.md
  docs/cookbook/react_agent.md
  docs/reference/generation/generation.md
  docs/reference/generation/structured_generation_explanation.md
  docs/reference/models/models.md
  docs/reference/models/transformers.md
  docs/stylesheets/extra.css
  docs/welcome.md
  mkdocs.yml
Labels: examples, documentation

#1113 Use relative coverage source paths
  .github/workflows/tests.yml
  pyproject.toml
Labels: bug, tests

#1124 Add missing CI matrix step
  .github/workflows/tests.yml
Labels: bug
