Repository dottxt-ai/outlines, pull requests merged in 2024-05, with the labels that each got.

#852 Remove the need to copy all tokens during basic generation
  outlines/fsm/fsm.py
  outlines/fsm/guide.py
  outlines/generate/generator.py
  outlines/integrations/transformers.py
  tests/fsm/test_fsm.py
  tests/fsm/test_guide.py
Labels: text, enhancement, optimization

#854 Add article with HF in README and documentation
  README.md
Labels: documentation

#865 Hotfix for CFG Generation
  outlines/generate/generator.py
Labels: bug, grammar

#868 Localize types
  docs/reference/types.md
  outlines/types/__init__.py
  outlines/types/locales.py
  outlines/types/phone_numbers.py
  outlines/types/zip_codes.py
  tests/test_types.py
Labels: enhancement

#877 Fix installation instructions
  docs/community/contribute.md
Labels: documentation

#874 Remove broken final state loop
  outlines/fsm/guide.py
  tests/fsm/test_fsm.py
  tests/fsm/test_guide.py
Labels: bug, structured generation

#897 Prevent Illegal Look-Around for OneOf in JSONSchema
  outlines/fsm/json_schema.py
  tests/fsm/test_json_schema.py
Labels: structured generation, JSON

#915 Use TQDM to track index compilation progress
  .pre-commit-config.yaml
  outlines/fsm/regex.py
  pyproject.toml
Labels: enhancement

#914 Allow json schema of `{}`, resulting in unconstrained json value
  outlines/fsm/json_schema.py
  tests/fsm/test_json_schema.py
Labels: bug, JSON

#929 Fix llamacpp caching by making `LlamaCppTokenizer` an outlines `Tokenizer`
  outlines/integrations/llamacpp.py
  outlines/models/llamacpp.py
  tests/generate/conftest.py
  tests/generate/test_integration_llamacpp.py
  tests/generate/test_integration_transformers.py
Labels: bug, llama.cpp
