Repository dottxt-ai/outlines, pull requests merged in 2024-04, with the labels that each got.

#775 Small typo fix in cookbook example
  docs/cookbook/classification.md
Labels: documentation

#783 Add nvidia to list of companies using Outlines
  docs/welcome.md
Labels: enhancement, documentation

#784 Add nvidia logo
  docs/logos/nvidia.png
Labels: enhancement, documentation

#793 Change white space pattern in llama.cpp test
  tests/generate/test_integration_llamacpp.py
Labels: bug, llama.cpp

#798 Switched order of AzureAsyncOpenAI to AsyncAzureOpenAI
  outlines/models/openai.py
Labels: bug, API models

#801 Add downloads badge
  README.md
Labels: enhancement, documentation

#802 Add a small grammar guide
  docs/reference/cfg.md
Labels: documentation, grammar

#804 Remove unused dependencies
  pyproject.toml
Labels: enhancement

#805 Update the README with articles on structured generation
  README.md
Labels: documentation

#815 Make `torch` and `transformers` imports optional
  docs/reference/models/transformers.md
  outlines/generate/api.py
  outlines/generate/generator.py
  outlines/models/transformers.py
  outlines/samplers.py
  pyproject.toml
Labels: enhancement

#816 Add page with projects from the community
  docs/community/examples.md
  docs/welcome.md
  mkdocs.yml
Labels: documentation

#817 Add documentation vLLM for multiple GPUs
  docs/reference/models/vllm.md
  docs/reference/serve/vllm.md
Labels: documentation

#819 Add DirectMerge article
  docs/community/examples.md
Labels: documentation

#803 Add cookbook to run Outlines on the cloud with Modal
  docs/cookbook/deploy-using-modal.md
  examples/modal_example.py
  mkdocs.yml
Labels: documentation

#829 Exclude escape character in JSON string fields
  outlines/fsm/json_schema.py
  tests/fsm/test_json_schema.py
Labels: structured generation, JSON

#830 Add tweets about Outlines
  docs/community/feedback.md
  docs/welcome.md
Labels: documentation

#825 Add `model_name` as an optional parameter for `azure_openai`
  outlines/models/openai.py
Labels: API models

#835 Fix typo in llama.cpp documentation
  docs/reference/models/llamacpp.md
Labels: documentation

#848 Add cookbook to run Outlines on the cloud with BentoML
  docs/cookbook/deploy-using-bentoml.md
  examples/bentoml/.bentoignore
  examples/bentoml/bentofile.yaml
  examples/bentoml/import_model.py
  examples/bentoml/requirements.txt
  examples/bentoml/service.py
  mkdocs.yml
Labels: documentation

#850 Add Gigax project to community
  docs/community/examples.md
Labels: documentation

#851 Add HF evaluation article
  docs/community/examples.md
Labels: documentation
