Repository dottxt-ai/outlines, pull requests merged in 2024-11, with the labels that each got.

#1256 Add PDF cookbook
  docs/cookbook/index.md
  docs/cookbook/read-pdfs.md
  mkdocs.yml
Labels: documentation

#1244 Add Anthropic integration
  outlines/models/__init__.py
  outlines/models/anthropic.py
  pyproject.toml
  tests/models/test_anthropic.py
Labels: enhancement, API models

#1289 Add link to YT channel and .txt blog
  README.md
Labels: documentation

#1228 add beam.cloud deployment example
  examples/beam-cloud/README.md
  examples/beam-cloud/app.py
Labels: documentation

#1207 Add jax compatible api
  benchmarks/bench_processors.py
  outlines/processors/base_logits_processor.py
  pyproject.toml
  tests/processors/test_base_processor.py
Labels: run-benchmarks

#1296 Fix library top-level imports
  docs/reference/models/llamacpp.md
  docs/reference/models/mlxlm.md
  docs/reference/models/openai.md
  docs/reference/models/transformers.md
  docs/reference/models/vllm.md
  outlines/models/transformers.py
  outlines/models/vllm.py
  pyproject.toml
  tests/generate/test_integration_transformers_vision.py
Labels: bug, enhancement, dependencies
