Repository dottxt-ai/outlines, pull requests merged in 2024-09, with the labels that each got.

#1139 Set the tokenizer versions in `test_create_fsm_index_tokenizer`
  tests/fsm/test_regex.py
  tests/generate/test_integration_llamacpp.py
Labels: bug, tests

#1144 Update logo size in documentation
  README.md
  docs/assets/images/logo-simple.png
  docs/index.md
  mkdocs.yml
Labels: documentation

#1160 Don't re-use logits processors in SequenceGeneratorAdapter, copy them
  outlines/generate/api.py
  tests/generate/test_generate.py
Labels: run_benchmarks

#1170 Fix benchmark workflow triggers
  .github/workflows/asv_benchmark_pr.yml
Labels: bug, tests, run-benchmarks

#1162 Reuse jinja environment for a prompt
  outlines/prompts.py
Labels: enhancement, run-benchmarks

#1175 Use Faster FSM
  .github/workflows/tests.yml
  benchmarks/bench_cfg_guide.py
  benchmarks/bench_json_schema.py
  benchmarks/bench_numba_compile.py
  benchmarks/bench_regex_guide.py
  benchmarks/common.py
  outlines/fsm/fsm.py
  outlines/fsm/guide.py
  outlines/fsm/parsing.py
  outlines/fsm/regex.py
  pyproject.toml
  tests/fsm/test_fsm.py
  tests/fsm/test_regex.py
  tests/generate/test_integration_transformers.py
Labels: run-benchmarks
