Repository dottxt-ai/outlines, pull requests merged in 2024-03, with the labels that each got.

#717 Allow specifying own Hugging Face tokenizer instance
  outlines/models/transformers.py
  tests/generate/test_integration_transformers.py
Labels: enhancement, transformers

#719 Put `prompt_token_ids`, `attentions_mask` and `weights` on the same device
  outlines/generate/api.py
Labels: bug, transformers

#721 Fixing Enum with only one element being ignored
  outlines/fsm/json_schema.py
  tests/fsm/test_json_schema.py
Labels: bug, structured generation

#727 Clean the `transformers` and `llamacpp` interfaces
  docs/reference/models/llamacpp.md
  docs/reference/models/transformers.md
  outlines/models/__init__.py
  outlines/models/exllamav2.py
  outlines/models/llamacpp.py
  outlines/models/mamba.py
  outlines/models/transformers.py
  tests/benchmark/conftest.py
  tests/fsm/test_regex.py
  tests/generate/test_integration_transformers.py
  tests/models/test_transformers.py
Labels: transformers, llama.cpp

#737 Add `Guide` interface
  docs/api/fsm.md
  mkdocs.yml
  outlines/fsm/guide.py
  outlines/generate/api.py
  outlines/generate/cfg.py
  outlines/generate/fsm.py
  outlines/generate/generator.py
  outlines/generate/regex.py
  outlines/generate/text.py
  outlines/models/llamacpp.py
  outlines/serve/vllm.py
  tests/benchmark/conftest.py
  tests/benchmark/test_benchmark_json_schema.py
  tests/benchmark/test_benchmark_regex_fsm.py
  tests/fsm/test_guide.py
  tests/generate/test_generator.py
  tests/test_grammars.py
Labels: enhancement, structured generation

#741 Restore FSM interface for backward compatibility
  outlines/fsm/fsm.py
  tests/fsm/test_fsm.py
Labels: enhancement

#742 Update the docstring of `exl2`
  outlines/models/exllamav2.py
Labels: documentation

#755 Add BibteX citation
  README.md
Labels: documentation
